* 2018--Present:
  Counsel to [[https://www.sec.gov/biography/commissioner-robert-j-jackson][Commissioner Robert J. Jackson Jr.]]\\
  Securities and Exchange Commission, Washington, D.C.

- I use economics and data science to inform policy.
- I advise on market structure, disclosure, asset management, and
  economic analyses.
- I provide technical assistance to other agencies, Capitol Hill, and
  the media.
- I assist in writing policy speeches and statements.


* 2016--2018: 
  Financial Economist Fellow \\
  Securities and Exchange Commission, Washington, D.C. \\
  [[http://www.sec.gov/dera][Division of Economic and Risk Analysis]]

- I studied the economic implications of rulemaking on financial markets.
  - I conducted [[https://ssrn.com/abstract=3195001][independent research]] suggesting that `speed bumps' may improve
    market quality, (see coverage in [[https://www.wsj.com/articles/study-finds-speed-bumps-help-protect-ordinary-investors-1528974002][Wall Street Journal]]).
- I was involved in modernizing the Commission's technology infrastructure
  through data science and cloud initiatives (see [[https://www.sec.gov/files/SEC_Strategic_Plan_FY18-FY22_FINAL_0.pdf][SEC Strategic Plan
  2018--2022]]).
- I coordinated with SROs to acquire and construct regulatory databases.
