
* [[https://ssrn.com/abstract=3673531][Index-Fund Governance: An Empirical Study of the Lending-Voting Tradeoff]]
/with Joshua Mitts and Haley Sylvester/

- Presented at JCLAW (2020*)

#+BEGIN_QUOTE
Institutional investors' role in shareholder voting is among the most hotly debated subjects in corporate governance. Some argue that institutions lack adequate incentives to effectively monitor managers; others contend that the largest institutions have developed analytical resources that produce informed votes. But little attention has been paid to the tradeoff these institutions face between voting their shares and earning profits—both for themselves and for the ultimate beneficiary of institutional funds—by lending those shares.

Using a unique dataset and a recent change in SEC rules as an empirical setting, we document a substantial increase in the degree to which large institutions lend shares rather than cast votes in corporate elections. We show that, after the SEC clarified funds’ power to lend shares rather than vote them at shareholder meetings, institutions supplied 58% more shares for lending immediately prior to those meetings. The change is concentrated in stocks with high index fund ownership; a difference-in-differences approach shows that supply increases from 15.6% to 22.3% at those stocks. Even when it comes to proxy fights, we show, stocks with high index ownership see a marked increase in shares available for lending immediately prior to the meeting. Overall, we show that loosening the legal constraints on institutional share lending has had significant implications for how index funds balance the lending-voting tradeoff.
#+END_QUOTE


* [[https://papers.ssrn.com/abstract=3600230][Vestigial Tails: Floor Brokers at the Close in Modern Electronic Markets]]
/with Dermot Murphy/

- Covered in the [[https://www.wsj.com/articles/coronavirus-shutdown-casts-doubt-on-value-of-exchange-trading-floors-11590053419][Wall Street Journal]], [[https://www.bloomberg.com/opinion/articles/2020-05-22/a-vaccine-with-a-poison-pill][Money Stuff (Bloomberg)]], [[https://www.economist.com/finance-and-economics/2020/05/25/covid-19-forced-trading-floors-to-close-theyll-be-back][The Economist]].
- Presented at University of Illinois Chicago (2020*), Rice University, SEC (2020*)

#+BEGIN_QUOTE
Closing auctions determine daily closing prices and trillions of dollars of net
asset values. We study closing auction market quality on NYSE and Nasdaq as
measured by the accuracy of indicative closing auction prices, volume, and order
imbalances. Closing auction market quality is significantly lower on NYSE
compared to Nasdaq due to the existence of a second-stage auction period on NYSE
which is exclusive to floor brokers. When NYSE closes its floor during the
COVID-19 pandemic, we find that NYSE auction quality improves. We use exogenous
shocks to impatient liquidity trader volume stemming from end-of-month portfolio
rebalancing periods and "triple witching" days to show that closing auction
market quality is worse on NYSE because impatient liquidity traders pool their
orders in the first-stage auction period. Consistent with this view, NYSE
auction quality deteriorates during our 2011-2018 sample period as passive
investing overtakes active management.
#+END_QUOTE


* [[https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3295980][Loan Syndication Networks]]
/with Jeffrey Harris, and Ioannis Spyridiopoulos/

- Presented at FMA (2019*)

#+BEGIN_QUOTE
Banks develop network connections through repeated co-syndication
relationships with multiple lenders. We create measures of network
centrality based on banks’ historical co-syndication ties, and find
that well-connected lenders are more likely to gain lead underwriter
status and offer better loan terms. Our results are robust to
variation in network connections generated by bank
consolidations. Well-connected banks offer lower spreads to firms with
higher levels of information asymmetry, underwrite loans faster, and
retain a smaller fraction of the loan. The evidence is more consistent
with recent theory suggesting networks mitigate information asymmetry
in syndicates, rather than superior screening or monitoring.
#+END_QUOTE


* [[https://ssrn.com/abstract=3195001][Intentional Access Delays, Market Quality, and Price Discovery: Evidence from IEX Becoming an Exchange]]

- Covered in the [[https://www.wsj.com/articles/study-finds-speed-bumps-help-protect-ordinary-investors-1528974002][Wall Street Journal (1)]] [[https://www.wsj.com/articles/sec-wont-release-speed-bump-study-it-promised-two-years-ago-1540401251][(2)]], [[https://www.theglobeandmail.com/business/article-trading-speed-bumps-protect-regular-investors-from-high-frequency/][Globe and Mail]], [[http://www.tradersmagazine.com/news/ecns_and_exchanges/sec-says-as-exchange-iex-helps-improve-market-quality-117836-1.html][Traders Magazine]], [[https://tabbforum.com/researches/intentional-access-delays-market-quality-and-price-discovery-evidence-from-iex-becoming-an-exchange][TabbFORUM]], [[https://www.ft.com/content/20d40032-9b0d-11e8-88de-49c908b1f264][Financial Times]], [[https://www.fastcompany.com/video/how-38-miles-of-cable-changed-the-stock-market-forever/UaSEVpma][Fast Company (Video)]]

- Presented at Securities and Exchange Commission (2019), DC Juniors
  Finance Conference (2019)
#+BEGIN_QUOTE
This paper exploits cross-sectional variation in trading activity and the
staggered securities phase-in when the Investors Exchange (IEX) becomes a
national securities exchange to study the effects of intentional access delays
on market quality and price discovery. Market quality improves after IEX becomes
an exchange for securities with high historical IEX market share. Price
discovery improves overall, although IEX's contribution to price discovery
remains small. Intermarket Sweep Order activity decreases overall, coinciding
with improvements in price discovery. In a second natural experiment where IEX's
ECN goes dark in 28 symbols there is no change in market quality or price
discovery. The findings in this paper suggest that protected markets with
symmetric speed bumps may be a feasible solution to deemphasize speed in lieu of
regulatory intervention.
#+END_QUOTE

