
* [[https://ssrn.com/abstract=3221017][Loan Syndication Networks]]
/with Jeffrey Harris, and Ioannis Spyridiopoulos/

#+BEGIN_QUOTE
We document a positive relationship between lender network centrality and the
ability to offer competitive bids in syndicated lending markets. Better
connected lenders are more likely to syndicate loans as lead arrangers, and
provide lower costs of borrowing. We exploit exogenous variation in network
structure resulting from bank mergers to provide evidence that greater
connectivity reduces firms' costs of borrowing. The effects are larger for
borrowers with higher levels of information asymmetry---consistent with recent
theory suggesting that superior networking facilitates information sharing and
coordination.
#+END_QUOTE

* [[https://ssrn.com/abstract=3195001][Intentional Access Delays, Market Quality, and Price Discovery: Evidence from IEX Becoming an Exchange]]

- Covered in the [[https://www.wsj.com/articles/study-finds-speed-bumps-help-protect-ordinary-investors-1528974002][*Wall Street Journal (1)*]] [[https://www.wsj.com/articles/sec-wont-release-speed-bump-study-it-promised-two-years-ago-1540401251][*(2)*]], [[https://www.theglobeandmail.com/business/article-trading-speed-bumps-protect-regular-investors-from-high-frequency/][*Globe and Mail*]], [[http://www.tradersmagazine.com/news/ecns_and_exchanges/sec-says-as-exchange-iex-helps-improve-market-quality-117836-1.html][*Traders Magazine*]], [[https://tabbforum.com/researches/intentional-access-delays-market-quality-and-price-discovery-evidence-from-iex-becoming-an-exchange][*TabbFORUM*]], [[https://www.ft.com/content/20d40032-9b0d-11e8-88de-49c908b1f264][*Financial Times*]]
#+BEGIN_QUOTE
This paper exploits cross-sectional variation in trading activity and the
staggered securities phase-in when the Investors Exchange (IEX) becomes a
national securities exchange to study the effects of intentional access delays
on market quality and price discovery. Market quality improves after IEX becomes
an exchange for securities with high historical IEX market share. Price
discovery improves overall, although IEX's contribution to price discovery
remains small. Intermarket Sweep Order activity decreases overall, coinciding
with improvements in price discovery. In a second natural experiment where IEX's
ECN goes dark in 28 symbols there is no change in market quality or price
discovery. The findings in this paper suggest that protected markets with
symmetric speed bumps may be a feasible solution to deemphasize speed in lieu of
regulatory intervention.
#+END_QUOTE


* [[https://ssrn.com/abstract=2564369][A comparison of some structural models of private information arrival]]
/with Jefferson Duarte, and Lance Young/ 
- *Forthcoming in Journal of Financial Economics*
- Presented at Rice University (2015), Texas A&M (2015*), Multinational Finance
  Society Conference (MFS, 2015*) *Best Paper Award*, China International
  Finance Conference (CICF, 2015*), Society of Financial Econometrics Conference
  (SoFiE, 2015*), Instituto Technologico Autonomo de Mexico Conference (ITAM,
  2015*), American Finance Association Conference (AFA, 2016), University of
  Washington (2016*), University of Virginia (McIntire) (2017*), Southern
  Methodist University (2017*).
- *[[https://edwinhu.github.io/pin/][Data and Previous Refereed Versions]]*
- Previously circulated under: "Does the PIN Model Mis-Identify Private Information and If So, What is the Alternative?"

#+BEGIN_QUOTE
We show that the PIN and the Duarte and Young (2009) (APIN) models do not match the variability of noise trade in the data and that this limitation has severe implications for how these models identify private information. We examine two alternatives to these models, the Generalized PIN model (GPIN) and the Odders-White and Ready (2008) model (OWR).  Our tests indicate that measures of private information based on the OWR and GPIN models are promising alternatives to the APIN’s $Adj.PIN$ and $PIN$
#+END_QUOTE


* [[https://ssrn.com/abstract=2139679][Financial Integration and Credit Democratization: Linking Banking Deregulation to Economic Growth]]
/with Elizabeth Berger, Alexander Butler, and Morad Zekhnini/

- *Revise and Resubmit Journal of Financial Intermediation*
- Presented at Rice University (2012*), Financial Management Association
  Conference (FMA 2013), Securities and Exchange Commission (SEC, 2014*),
  Fordham University (2014*), University of Cincinnati (2014*), University of
  Kentucky (2014*), Yale School of Management (2015*).

#+BEGIN_QUOTE
We document a positive effect of financial integration on economic growth. Using
US state-by-state financial deregulations, we find that economic growth occurred
in states where bank deregulation solved a capital immobility problem. We use a
matching method that constructs synthetic counterfactual states to identify the
channels that link bank deregulation to financial integration, and thereby to
economic growth. Our results reveal a correlation between financial integration
and subsequent banking sector changes including improved bank efficiency, better
lending and borrowing rates, and an expansion in loan recipients. We show that
financial integration democratizes lending and spurs economic growth.
#+END_QUOTE
